# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: fr

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Paris

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: TRTN - Pentesting & CTF # Le titre principal
tagline: Partage de rapports, tutoriels, et aventures en cybersécurité. # Le sous-titre
description: >- # utilisé pour les balises SEO et flux atomiques
  Un site dédié au pentesting, aux CTFs, et aux connaissances en cybersécurité.

# Fill in the protocol & hostname for your site.
url: "https://trbarry.github.io" # Utilisez uniquement la partie "racine" de votre URL
baseurl: "/Trtn.Github.io" # Spécifiez le sous-dossier si votre site est hébergé dans un dépôt avec un nom spécifique

github:
  username: Trbarry # Remplacez par votre nom d'utilisateur GitHub

twitter:
  username: # Remplacez par votre nom Twitter

social:
  name: Tristan Barry # Votre nom complet
  email: barry43@hotmail.fr # Adresse e-mail affichée
  links:
    - https://github.com/Trbarry # Lien vers votre profil GitHub
    - https://linkedin.com/in/tristan-barry-43b91b330 # Lien vers votre LinkedIn

# Site Verification Settings
webmaster_verifications:
  google: # Laissez vide ou ajoutez un code de vérification
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings (facultatif)
analytics:
  google:
    id: # Ajoutez votre Google Analytics ID ici

# Prefer color scheme setting.
theme_mode: dark # Forcer le mode sombre (ou laissez vide pour suivre les préférences système)

# Avatar et prévisualisation sociale
avatar: "/assets/img/logo.png" # Chemin vers votre logo (à ajouter dans le dossier assets)
social_preview_image: "/assets/img/social-preview.png" # Image utilisée dans les partages sociaux

# Table of contents (TOC) dans les articles
toc: true

comments:
  provider: giscus # Activez Giscus pour les commentaires (autres options : disqus, utterances)
  giscus:
    repo: Trbarry/Trtn.Github.io
    repo_id: votre-repo-id
    category: Discussions
    category_id: votre-category-id
    mapping: pathname

pwa:
  enabled: true # Activer la fonction PWA (Progressive Web App)
  cache:
    enabled: true

paginate: 10 # Nombre d’articles affichés par page

# Archives et catégories
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

defaults:
  - scope:
      path: "" # Tous les fichiers du projet
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
